name: Publish to Comfy Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

permissions:
  contents: read

jobs:
  publish-node:
    name: Publish custom node
    runs-on: ubuntu-latest
    if: github.repository_owner == 'opvelll'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish node
        uses: Comfy-Org/publish-node-action@1.0.1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
